# Generated by Django 2.0.1 on 2018-01-29 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_auto_20180129_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labresult',
            name='lab',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='coreapp.Laboratory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='labresult',
            name='lab_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coreapp.LabRequest', unique=True),
        ),
    ]
