# Generated by Django 2.0.1 on 2018-01-30 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_auto_20180129_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labresult',
            name='lab_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='coreapp.LabRequest'),
        ),
    ]
