# Generated by Django 2.0.1 on 2018-01-30 12:36

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0006_labresult_test_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
    ]
