# Generated by Django 2.0.1 on 2018-01-30 13:04

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0007_auto_20180130_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True),
        ),
    ]
