# Generated by Django 2.0.1 on 2018-01-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0008_auto_20180130_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(help_text='yy-mm-dd'),
        ),
    ]
