# Generated by Django 2.0.1 on 2018-01-31 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0009_auto_20180131_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labresultupdated',
            name='lab_request',
        ),
        migrations.DeleteModel(
            name='LabResultUpdated',
        ),
    ]
