# Generated by Django 2.0.1 on 2018-01-31 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0011_auto_20180131_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laboratory',
            options={'ordering': ['name'], 'verbose_name_plural': 'laboratories'},
        ),
    ]
