# Generated by Django 2.0.1 on 2018-01-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0012_auto_20180131_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
